### ISSUE TITLE
Using the ML-Phonetic-Analyser on MacOS

### ISSUE THREAD

**Issue by meghavarshini** [kavyamanohar/ml-phonetic-analyser#1]
Since all the instructions in the ReadMe are for a Debian system, this post is about my experience installing and using the G2P on the MacOS 10.13.3.

- The HFST that I needed to use was a legacy version (3.8.1) that I downloaded from [sourceforge](https://sourceforge.net/projects/hfst/files/hfst/archive/). Installing HFST from the link provided resulted in errors while using the 'make' command that I was unable to resolve.

- While using the 'make' command during installation, I encountered the following errors: (Despite these two error messages, I have not encountered any problems while using the code).
    * input filter.fst : line 5
    * alphabet.fst:  line 66

- In the 'Examples' subsection 'Generate IPA sequence from malayalam script', the code worked when I typed **'python3 python/IPAGenerator.py'** and **'python3 python/IPAGenerator.py -i path/to/inputfile.txt -o path/to/outputfile.txt'**, as the python codes are in the subfolder 'python', not the main folder.

**Comment by kavyamanohar** [comment]
I have updated the code with some major revisions in the internal implementation. The system now has 

- a syllablizer. Splits input word into syllables.
- g2p mapper. It produces IPA corresponding to Malayalam script with IPA tags as well.

I have stopped using fst to remove IPA tags. Planning to do it in python soon.
